import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { useQuery } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { usePageView } from '@/hooks/usePageView';
import { CourseCard } from '@/components/courses/CourseCard';
import { User, Star, Instagram, Linkedin, Globe, Youtube, Twitter, Play, ChevronDown } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import { initPixel, trackEventFor } from '@/lib/metaPixel';
import { SEO } from '@/components/SEO';
import { CreatorProfileSkeleton } from '@/components/ui/page-skeletons';

function StarRating({ value }: { value: number }) { return <div className="flex gap-1">{[1, 2, 3, 4, 5].map((star) => <Star key={star} className={`h-5 w-5 ${star <= value ? 'fill-yellow-400 text-yellow-400' : 'text-muted-foreground'}`} />)}</div>; }
const socialIcons: Record<string, any> = { instagram: Instagram, linkedin: Linkedin, twitter: Twitter, youtube: Youtube, website: Globe };

export default function CreatorProfilePage() {
  const { slug } = useParams<{ slug: string }>();
  const [visibleReviews, setVisibleReviews] = useState(3);
  const { data: creator, isLoading } = useQuery({ queryKey: ['creator', slug], queryFn: async () => { const { data, error } = await supabase.rpc('get_public_creator_profile', { _slug: slug! }); if (error) throw error; return data?.[0] ?? null; } });
  usePageView('creator_profile', creator?.id);
  useEffect(() => { if (!slug) return; supabase.rpc('get_creator_pixel_id', { _creator_slug: slug }).then(({ data }) => { if (data) { initPixel(data as string); trackEventFor(data as string, 'PageView'); } }); }, [slug]);
  const { data: courses } = useQuery({ queryKey: ['creator-courses', creator?.id], queryFn: async () => { const { data, error } = await supabase.from('courses').select('*').eq('creator_id', creator!.id).eq('status', 'published').order('created_at', { ascending: false }); if (error) throw error; return data; }, enabled: !!creator?.id });
  const { data: reviews = [] } = useQuery({ queryKey: ['creator-reviews', creator?.id], queryFn: async () => { const { data, error } = await supabase.rpc('get_creator_reviews', { _creator_id: creator!.id }); if (error) throw error; return data ?? []; }, enabled: !!creator?.id });
  if (isLoading) return <CreatorProfileSkeleton />;
  if (!creator) return <div className="page-container text-center py-20"><h1 className="text-2xl font-bold mb-4">Creador no encontrado</h1><Button asChild><Link to="/courses">Ver cursos</Link></Button></div>;
  const links: any[] = [];
  const embedUrl: string | null = null;
  const avgRating = reviews.length ? (reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length).toFixed(1) : null;
  const shownReviews = reviews.slice(0, visibleReviews);

  return <div className="page-container"><SEO title={`${creator.name || 'Creador'} — NOVU`} description={creator.bio?.trim() || `Cursos y productos digitales de ${creator.name || 'este creador'} en NOVU.`} path={`/creator/${creator.creator_slug || slug}`} type="profile" image={creator.avatar_url || undefined} />
    <div className="bg-gradient-to-br from-primary/10 to-background rounded-2xl p-8 mb-12"><div className="grid grid-cols-1 lg:grid-cols-2 gap-8"><div className="flex flex-col md:flex-row items-center md:items-start gap-6"><div className="w-24 h-24 rounded-full bg-primary/10 flex items-center justify-center overflow-hidden shrink-0">{creator.avatar_url ? <img src={creator.avatar_url} alt={creator.name || 'Creador'} className="w-full h-full object-cover" /> : <User className="h-12 w-12 text-primary" />}</div><div className="text-center md:text-left flex-1"><h1 className="text-2xl font-bold">{creator.name}</h1><p className="text-primary font-medium mt-1">Creador de cursos</p>{avgRating && <div className="flex items-center gap-2 mt-2 justify-center md:justify-start"><Star className="h-5 w-5 fill-yellow-400 text-yellow-400" /><span className="font-semibold">{avgRating}</span><span className="text-muted-foreground text-sm">({reviews.length} evaluaciones)</span></div>}{creator.bio && <p className="text-muted-foreground mt-3 text-sm">{creator.bio}</p>}{links.length > 0 && <div className="flex flex-wrap gap-2 mt-4 justify-center md:justify-start">{links.map((link: any, index: number) => { const Icon = socialIcons[link.type] || Globe; return <a key={index} href={link.url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-background border rounded-full text-sm hover:border-primary transition-colors"><Icon className="h-4 w-4" />{link.label}</a>; })}</div>}</div></div>{embedUrl && <div className="flex flex-col"><h3 className="text-sm font-medium mb-2 flex items-center gap-2"><Play className="h-4 w-4" />Conóceme</h3><div className="aspect-video rounded-xl overflow-hidden bg-muted flex-1"><iframe src={embedUrl} className="w-full h-full" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen /></div></div>}</div></div>
    <div className="mb-12"><h2 className="text-2xl font-bold mb-6">Cursos publicados</h2>{courses?.length ? <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">{courses.map((course) => <CourseCard key={course.id} id={course.id} slug={course.slug} title={course.title} description={course.description} coverImageUrl={course.cover_image_url} priceCLP={course.price_clp} level={course.level} durationMinutes={course.duration_minutes_est} creatorName={creator.name} creatorSlug={creator.creator_slug} />)}</div> : <p className="text-muted-foreground">Este creador aún no tiene cursos publicados.</p>}</div>
    <div><h2 className="text-2xl font-bold mb-6">Evaluaciones</h2>{shownReviews.length ? <div className="grid grid-cols-1 md:grid-cols-3 gap-4">{shownReviews.map((review: any) => <Card key={review.id}><CardContent className="pt-6"><div className="flex items-start gap-3"><div className="w-10 h-10 rounded-full bg-muted flex items-center justify-center shrink-0">{review.reviewer_avatar_url ? <img src={review.reviewer_avatar_url} alt="" className="w-full h-full object-cover rounded-full" /> : <User className="h-5 w-5 text-muted-foreground" />}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="font-medium truncate">{review.reviewer_name || 'Usuario'}</p><span className="text-xs text-muted-foreground shrink-0">{new Date(review.created_at).toLocaleDateString('es-CL')}</span></div><StarRating value={review.rating} />{review.product_title && <p className="text-xs text-muted-foreground mt-2">{review.product_type === 'ebook' ? 'E-book' : review.product_type === 'session' ? 'Agendamiento' : review.product_type === 'event' ? 'Evento' : review.product_type === 'community' ? 'Comunidad' : 'Curso'} · {review.product_title}</p>}{review.comment && <p className="text-muted-foreground mt-2">{review.comment}</p>}<p className="text-xs text-primary mt-3">Comprador verificado por NOVU</p></div></div></CardContent></Card>)}</div> : <p className="text-muted-foreground">Aún no hay evaluaciones para este creador.</p>}{visibleReviews < reviews.length && <div className="flex justify-center mt-6"><Button variant="outline" onClick={() => setVisibleReviews((count) => count + 3)}>Cargar más evaluaciones <ChevronDown className="h-4 w-4 ml-2" /></Button></div>}</div>
  </div>;
}
