// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// 🔥 Hardcode temporal para asegurar que Lovable use el Supabase correcto
const SUPABASE_URL = "https://kfyyzecqvjahdealixdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "PEGA_ACA_TU_SB_PUBLISHABLE_KEY_COMPLETA";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});

